packages:
  - 01-ssg
  - 02-ssr
  - 03-rsc-no-framework
  - 04-rsc-with-next-js
  - 05-react-performance
  - 06-optimistic
  - 07-deferred
  - 08-transitions
allowBuilds:
  esbuild: true
  sharp: true
  sqlite3: true
  unrs-resolver: true
